apiVersion: apps/v1
kind: Deployment
metadata:
  name: penultimo
  namespace: presidential-paradise
  labels:
    app: penultimo
    keel.sh/policy: force
spec:
  # Multiple replicas are _not_ supported
  replicas: 1
  selector:
    matchLabels:
      app: penultimo
  template:
    metadata:
      labels:
        app: penultimo
    spec:
      containers:
      - name: penultimo
        image: registry.xirion.net/library/penultimo
        env:
          - name: DISCORD_TOKEN
            value: CHANGE_ME
          - name: PYTHONUNBUFFERED
            value: "1"
